services:

  movie-service:
    image: sandeep07k/movie-service:1.0.0
    container_name: movie-service
    environment:
      MONGODB_URI: ${MONGODB_URI}
    ports:
      - "8082:8082"
    networks:
      - showtime-network
    logging:
      driver: awslogs
      options:
        awslogs-region: ap-south-1
        awslogs-group: /showtime/movie-service
        awslogs-stream: movie-service
        awslogs-create-group: "true"

  showtime-gateway:
    image: sandeep07k/showtime-gateway:1.0.0
    container_name: showtime-gateway
    ports:
      - "8080:8080"
    depends_on:
      - movie-service
    networks:
      - showtime-network
    logging:
      driver: awslogs
      options:
        awslogs-region: ap-south-1
        awslogs-group: /showtime/gateway
        awslogs-stream: showtime-gateway
        awslogs-create-group: "true"

networks:
  showtime-network:
    driver: bridge