name: Deploy ShowTime

on:
  workflow_dispatch:
    inputs:
      movie_service_tag:
        description: "Movie Service Docker tag"
        required: true
      gateway_tag:
        description: "Gateway Docker tag"
        required: true

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          script: |
            cd ~/showtime-infrastructure

            export MOVIE_SERVICE_TAG="${{ inputs.movie_service_tag }}"
            export GATEWAY_TAG="${{ inputs.gateway_tag }}"

            export MONGODB_URI="${{ secrets.MONGODB_URI }}"

            docker compose pull
            docker compose up -d
            docker compose ps
